Allow user initiated navigation when the tour is active
hakimio/ngx-ui-tour pull request #111
Opened 2023-03-07 10:45 UTC by mivanyna

2023-03-07 10:49 UTC, hakimio commented
- Docs and changelog have to be updated
- You don't handle the case when the user clicks back/forward browser buttons. In this case the tour should end, even when `allowUserInitiatedNavigation` is true
- Might be a good idea to update defaults

2023-03-07 11:09 UTC, mivanyna commented
Yes, still working on it. Will ping you once it's done.

Which defaults? In docs?

2023-03-07 11:19 UTC, mivanyna commented
@hakimio Do you have any good description for the property?

`Allow user navigate to other routes not ending the tour. False by default (optional)`

2023-03-07 12:13 UTC, hakimio commented
> Which defaults? In docs?

https://github.com/hakimio/ngx-ui-tour/blob/6356be87bea7b1754a08ce90e132e41a0ff83d59/projects/ngx-ui-tour-core/src/lib/tour.service.ts#L60

2023-03-07 13:02 UTC, mivanyna commented
I would even remove boolean properties with default value `false`.  Why keep them?

2023-03-07 13:03 UTC, hakimio commented
I like explicitly defined defaults.

2023-03-07 13:14 UTC, mivanyna commented
@hakimio please check

2023-03-07 14:21 UTC, mivanyna commented
Should I update all the CHANGELOG files?

2023-03-08 13:54 UTC, hakimio requested changes

2023-03-08 13:54 UTC, hakimio commented on projects/ngx-ui-tour-console/CHANGELOG.md
> +- Allow user initiated navigation when the tour is active.
> New `allowUserInitiatedNavigation` config. Enable to keep the tour open while the user navigates to a different page. Can cause the tour to get "stuck" if active anchor element is removed from the DOM after the navigation. The option is not related to navigation initiated by the UI tour and should not be enabled in most cases.

Also, new features increase minor version - not patch. [semver.org](https://semver.org/)

2023-03-08 13:54 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour.service.ts
> +                    if (!this.navigationStarted && (event.navigationTrigger === 'popstate' || !this.currentStep.allowUserInitiatedNavigation)) {
Use variables to make the code more readable.
```ts
const browserBackBtnPressed = event.navigationTrigger === 'popstate',
    userNavigationAllowed = this.currentStep.allowUserInitiatedNavigation;

    if (!this.navigationStarted && (browserBackBtnPressed || !userNavigationAllowed) {}
```

2023-03-08 13:54 UTC, hakimio commented on src/app/shared/step-config/step-config.component.html
> +            Allow user navigate to other routes not ending the tour. False by default (optional)
> Enable to keep the tour open while the user navigates to a different page. Can cause the tour to get "stuck" if active anchor element is removed from the DOM after the navigation. The option is not related to navigation initiated by the UI tour and should not be enabled in most cases.

2023-03-09 11:55 UTC, hakimio requested changes

2023-03-09 11:55 UTC, hakimio commented on src/app/shared/step-config/step-config.component.html
> +        <div tourAnchor="config.allowUserInitiatedNavigation" style="cursor: pointer;">
I don't think the `tourAnchor` is used.

2023-03-09 12:09 UTC, hakimio commented on src/app/shared/step-config/step-config.component.html
> +        <div tourAnchor="config.allowUserInitiatedNavigation" style="cursor: pointer;">
And why does it need `style="cursor: pointer;"`?

2023-03-10 09:12 UTC, hakimio requested changes

2023-03-10 09:12 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour.service.ts
> +                      userNavigationAllowed = this.currentStep.allowUserInitiatedNavigation;
Might be a good idea to use optional chaining in case `currentStep` is undefined.

2023-03-10 09:20 UTC, merged