Add popoverClass input for hostDirectives config for tourAnchor direc…
hakimio/ngx-ui-tour pull request #113
Opened 2023-03-07 18:04 UTC by mivanyna

…tive

2023-03-08 14:03 UTC, hakimio commented
- I don't want to add any inputs to the directive. All options should be set in tour step config.
- To keep it consistent, I would prefer to use the same config name like in `ngx-bootstrap` UI implementation: [containerClass](https://github.com/hakimio/ngx-ui-tour/blob/6356be87bea7b1754a08ce90e132e41a0ff83d59/projects/ngx-ui-tour-ngx-bootstrap/src/lib/tour-anchor.directive.ts#L53).
- Might be a good idea to update the docs with example usage like it's done in `ngx-bootstrap` demo.

2023-03-08 14:58 UTC, mivanyna commented
@hakimio please check

2023-03-09 12:07 UTC, hakimio requested changes

2023-03-09 12:07 UTC, hakimio commented on src/app/ng-bootstrap/ng-bootstrap.component.scss
> +    .custom-tour-class {
Can we reuse the same CSS instead of duplicating it?

2023-03-09 12:07 UTC, hakimio commented on src/app/ng-bootstrap/ng-bootstrap.component.ts
> +import { INgbStepOption } from '../../../projects/ngx-ui-tour-ng-bootstrap/src/lib/step-option.interface'
Please keep the original formatting.

2023-03-09 15:32 UTC, mivanyna commented on projects/ngx-ui-tour-ng-bootstrap/src/lib/tour-anchor.directive.ts
> +            this.popoverDirective.popoverClass += ` ${step.popoverClass}`;
User can add it at any time.
If I hardcode the class like `tour-step` it might intersect with other library styles.

2023-03-09 15:36 UTC, mivanyna commented on src/app/ng-bootstrap/ng-bootstrap.component.scss
> +    .custom-tour-class {
done

2023-03-09 17:26 UTC, hakimio commented on projects/ngx-ui-tour-ng-bootstrap/src/lib/tour-anchor.directive.ts
> +            this.popoverDirective.popoverClass += ` ${step.popoverClass}`;
So, if you don't have initial `popoverDirective.popoverClass` value, why do you need to append it instead of just setting directly?

2023-03-09 17:34 UTC, mivanyna commented on projects/ngx-ui-tour-ng-bootstrap/src/lib/tour-anchor.directive.ts
> +            this.popoverDirective.popoverClass += ` ${step.popoverClass}`;
Fixed already

2023-03-10 09:18 UTC, hakimio requested changes

2023-03-10 09:18 UTC, hakimio commented on src/app/ng-bootstrap/ng-bootstrap.component.ts
> +import {INgbStepOption} from '../../../projects/ngx-ui-tour-ng-bootstrap/src/lib/step-option.interface'
Don't import anything directly from the projects folder. All the imports should be from `ngx-ui-tour-ng-bootstrap`.

2023-03-10 09:44 UTC, hakimio requested changes

2023-03-10 09:44 UTC, hakimio commented on projects/ngx-ui-tour-ng-bootstrap/CHANGELOG.md
> +- New `popoverClass` config. Set Custom Popover CSS Class.
```
- New `popoverClass` config. Can be used to set custom popover CSS class.
```

2023-03-10 09:44 UTC, hakimio commented on src/app/ng-bootstrap/ng-bootstrap.component.ts
> +import {IStepOption} from 'ngx-ui-tour-ng-bootstrap';
Combine in the first import like it was before.

2023-03-10 09:56 UTC, hakimio approved these changes

2023-03-10 09:58 UTC, merged