Support overflowing anchors
hakimio/ngx-ui-tour pull request #154
Opened 2023-10-13 11:19 UTC by EliotRagueneau

Hi @hakimio ,

Regarding the two issues I created on this https://github.com/hakimio/ngx-ui-tour/issues/152 and https://github.com/hakimio/ngx-ui-tour/issues/153, I've added support for anchors overflowing their scrollContainer.

I tried to follow your style of code.

Regarding the scroll issue, my fix shouldn't change the previous behaviour unless the anchor is indeed overflowing its scrollContainer, and the user configured at least one of `preferredScrollTargetX` and `preferredScrollTargetY`. 

According to you this is a rare and specific case so it shouldn't change break anything for the vast majority.

2023-10-13 11:26 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +                block: options.preferredScrollTarget.y ?? 'nearest',
Is there any reason here to use any other alignment apart from `start`?

2023-10-13 12:51 UTC, EliotRagueneau commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +                block: options.preferredScrollTarget.y ?? 'nearest',
Not sure, by default most people would be using 'start' for sure, but it doesn't hurt to offer the possibility I guess.
Maybe some users would want to target the end of their anchor rather than it's top for some reason? Or the nearest? It's definetly not my case, but maybe it would apply elsewhere

2023-10-13 12:53 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +                block: options.preferredScrollTarget.y ?? 'nearest',
Keep it simple and implement only want you actually need.
Adding needless extra options does hurt because it makes the library harder to maintain.

2023-10-13 12:54 UTC, EliotRagueneau commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +                block: options.preferredScrollTarget.y ?? 'nearest',
As you prefer

2023-10-13 13:10 UTC, EliotRagueneau commented
Just removed the options I originally, and everything related to horizontal overflow as I don't need it

2023-10-13 13:27 UTC, hakimio requested changes

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-backdrop.service.ts
> +            elementBoundingRect = rectangle ?? isHeightOverflowing(this.targetHtmlElement, scrollContainer) ? getOverlap(this.targetHtmlElement, scrollContainer) : this.targetHtmlElement.getBoundingC
This line needs to be refactored.

2023-10-13 13:27 UTC, hakimio commented on src/app/shared/step-config/step-config.component.ts
> +  selector: 'app-step-config',
Why did you change formatting in this file?

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/is-height-overflowing.ts
> +export function isHeightOverflowing(element: HTMLElement, scrollContainer: HTMLElement): boolean {
Since the file contains two different utility functions, maybe it makes sense to name the file sth other than `is-height-overflowing.ts`? Maybe `overflow-utils`, sth similar?

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/is-height-overflowing.ts
> +    rectA = element.getBoundingClientRect(),
Let's put `rectA` and `const` on the same line.

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-ng-bootstrap/package.json
> +    "ngx-ui-tour-core": "11.0.5"
The package version needs to bumped as well. Not only the dependency.

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-core/CHANGELOG.md
> +# [11.0.5](https://github.com/hakimio/ngx-ui-tour) (2023-10-13)
All changelogs have to be updated.

2023-10-13 13:27 UTC, hakimio commented on projects/ngx-ui-tour-core/CHANGELOG.md
> +- Avoid problems when anchors are overflowing their scrollContainer
Let's just simplify this: `Fix backdrop and scroll position when anchor element's height exceeds its scroll container's height`.

2023-10-13 13:30 UTC, EliotRagueneau commented on src/app/shared/step-config/step-config.component.ts
> +  selector: 'app-step-config',
Sorry I'm used to my auto formatting, cancelling that right away

2023-10-16 09:01 UTC, hakimio requested changes

2023-10-16 09:14 UTC, EliotRagueneau commented
Hi @hakimio, sorry about those links, good that you spotted those!
Also reverted the changes on step-config.component.ts

2023-10-16 09:25 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +        } else if (OverflowUtils.isHeightOverflowing(htmlElement, scrollContainer)) {
If it's overflowing, maybe it should align to the top even when `center` option is enabled?

2023-10-16 11:50 UTC, EliotRagueneau commented on projects/ngx-ui-tour-core/src/lib/scrolling.service.ts
> +        } else if (OverflowUtils.isHeightOverflowing(htmlElement, scrollContainer)) {
Originally, I did it this way because I didn't want to change the default behaviour on centering, aka if the option is activated, it is overriding all the other possibilities.
Changing the order of the `if` would imply changing the center semantics which I wanted to avoid, but if you are fine with it, I'm perfectly fine with making the overflow the first check.

My original proposition with the introduction of the different options was allowing users to select which behaviour they wanted on overflow, which kinda solved this problem let's say.

Anyway, if you prefer the overflow to be the first check, I'll follow you on that, I let you make the decision on this.

2023-10-17 07:17 UTC, merged

2023-10-17 08:01 UTC, hakimio commented
Thank you for your contribution 🙂

2023-10-17 09:48 UTC, EliotRagueneau commented
Thank you for your patience and reactiveness!