New Directive "tourAnchorOverlay"
hakimio/ngx-ui-tour pull request #161
Opened 2023-11-16 14:21 UTC by phrei

In discussion #159 I had the following problem:

I'm using an external component (in this case a calendar component) that contains a button group to switch views. I'm not able to set the `tourAnchor`-Directive on this button group (as the code is not in my domain).

My first solution was to create a `div` and position it absolutely over this button group and use the `tourAnchor`-Directive on this new `div`. If the layout changed somehow and these buttons were not in the same place anymore or changed in dimension, the absolutely positioned `div` was wrong (especially visible, if backdrop is enabled).

So instead of positioning this "artificial" tourAnchor-DIV I've created a directive which receives a CSS selector. This directive finds the element I want to overlay, gets it's bounding rect and sets the `div`'s position and dimensions accordingly.

In this [branch](https://github.com/phrei/ngx-ui-tour/tree/task-Demo-For-TourAnchorOverlay) you can see a demo of the directive. As a test I try to highlight the label of the button instead of the whole button (to showcase an element, that is not in my domain but in angular material's).

Additionally theres an Input for padding (which uses the technique from your docs to set padding and remove margin).

2023-11-30 15:33 UTC, hakimio requested changes

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +@Directive({
Maybe a component where you can fully control all the styles might be a better idea? I don't think this would work on any kind of element.

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +    @Input() public tourAnchorOverlay: string;
Maybe this input should be `required`?

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +    @Input() public tourAnchorOverlayPadding: number = 0;
Why do you need this when we already have `backdropConfig.offset` step config?

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +        el.nativeElement.style.position = 'absolute';
Maybe just use host binding instead? Or in case of a component, simply use `styles` component option.

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +        if (this.tourAnchorOverlay) {
Is there any point of not specifying this input?

2023-11-30 15:33 UTC, hakimio commented on projects/ngx-ui-tour-core/src/lib/tour-anchor-overlay.directive.ts
> +            let element = document.querySelector(this.tourAnchorOverlay) as HTMLElement;
Accessing `document` directly will give a bad time for `SSR` users. Might be a better idea to inject `DOCUMENT`.

2023-12-05 16:09 UTC, phrei commented
@hakimio Your solution definitely looks a lot neater! I'm totally fine with closing this pull request.

2023-12-05 19:00 UTC, hakimio commented
@phrei It's still your PR. I only made a suggestion.
If you want to have this feature, you still have to:
- update all tour UIs
- update all changelogs
- update documentation

Whether you update this PR or create a new one is your choice.

2023-12-06 07:38 UTC, phrei commented
@hakimio Oh, okay. Sure, I'll take care of that as soon as possible.

2024-06-26 12:55 UTC, hakimio commented
`<tour-proxy-anchor>` was added in `v13`.

2024-06-26 12:55 UTC, closed without merging

2024-07-16 15:10 UTC, AMZALE commented
looks like it is not added