issue-165 Resetting the "direction" to default value upon ending the tour
hakimio/ngx-ui-tour pull request #167
Opened 2024-01-25 17:27 UTC by alex4ndern

Regarding https://github.com/hakimio/ngx-ui-tour/issues/165

2024-01-25 17:31 UTC, hakimio commented
You still need to:
- update all changelogs
- bump version numbers in all library `package.json` files

2024-01-25 18:05 UTC, alex4ndern commented
> You still need to:
> 
> * update all changelogs
> * bump version numbers in all library `package.json` files

Like this?

2024-01-26 10:15 UTC, hakimio requested changes

2024-01-26 10:15 UTC, hakimio commented on projects/ngx-ui-tour-console/CHANGELOG.md
> +- Tour is now able to restart even if it was closed right after navigating to the previous step, while the first step is optional and not available
`Fix issue preventing the tour from starting when it was closed after navigating back, while the first step is optional and not available.`

2024-01-26 10:15 UTC, hakimio commented on projects/ngx-ui-tour-console/package.json
> +  "version": "12.0.1",
`ngx-ui-tour-core` dependency have to be updated as well:
```json
  "dependencies": {
    "tslib": "^2.0.0",
    "ngx-ui-tour-core": "12.0.1"
  }

```

2024-01-26 10:15 UTC, closed without merging

2024-01-26 10:16 UTC, alex4ndern commented
Will create a new PR soon

2024-01-26 10:16 UTC, hakimio commented
@alex4ndern why did you close this?

2024-01-26 10:18 UTC, alex4ndern commented
> @alex4ndern why did you close this?

Wanted to update the Author properly, will reopen a new one soon, sorry

2024-01-26 10:32 UTC, alex4ndern commented
https://github.com/hakimio/ngx-ui-tour/pull/168
here is the new one